name: Documentation

on:
  push:
    branches:
    - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-22.04
    container:
      image: swift:6.0-jammy@sha256:1ad73b8f2a2300c650da0949519418565661d802765b9a99435df22bc947e2b4

    steps:
    - uses: actions/checkout@v7.0.1
    - name: Set up Pages
      uses: actions/configure-pages@v6.0.0
    - name: Generate Docs (en_US)
      run: |
        mkdir -p ./docs/en_us
        swift package --allow-writing-to-directory ./docs/en_us \
        generate-documentation --target "User_Documentation_en_US" \
        --disable-indexing \
        --transform-for-static-hosting \
        --hosting-base-path "wallpaper-player-mac/en_us" \
        --output-path ./docs/en_us
    - name: Generate Docs (zh_CN)
      run: |
        mkdir -p ./docs/zh_cn
        swift package --allow-writing-to-directory ./docs/zh_cn \
        generate-documentation --target "User_Documentation_zh_CN" \
        --disable-indexing \
        --transform-for-static-hosting \
        --hosting-base-path "wallpaper-player-mac/zh_cn" \
        --output-path ./docs/zh_cn
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5.0.0
      with:
        path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs

    steps:
    - name: Deploy Docs
      id: deployment
      uses: actions/deploy-pages@v5.0.0
